# Application configuration for Heimdall
heimdall.logging.rest.enabled=true
heimdall.logging.service.enabled=true
heimdall.logging.repository.enabled=true
heimdall.logging.controlleradvice.enabled=true
heimdall.logging.logstash.enabled=false
heimdall.logging.logstash.host=localhost
heimdall.logging.logstash.port=5000

# Application configuration for Mimir
mimir.output.path=docs/

# Application configuration for Loki
loki.enabled=true

# Logging configuration
logging.level.root=INFO

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.application.name=baldr
spring.docker.network=asgard-network