# Application configuration for Heimdall
heimdall.logging.rest.enabled=true
heimdall.logging.service.enabled=true
heimdall.logging.repository.enabled=true
heimdall.logging.controlleradvice.enabled=true

# Application configuration for Mimir
mimir.output.path=docs/

# Application configuration for Loki
loki.enabled=true

logging.level.root=INFO

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update